/*
 * precision_config.h
 *
 * Auto-generated by python/pack_mixed.py --mcu-precision-header.
 * Per-tensor INT2 precision config for the active model.
 *
 * Both INT2 and INT4 packed weights live under TensorType.INT4 in the
 * FlatBuffer (TFLite has no INT2 type), so the MCU pre-unpack dispatcher
 * needs an explicit list of subgraph tensor indices that should be
 * treated as INT2.
 *
 * Source model: models/mobilenet_v1_cifar10/mobilenet_v1_cifar10_p1_L22_int2_dw8.tflite
 */

#ifndef PRECISION_CONFIG_H_
#define PRECISION_CONFIG_H_

#include <cstdint>

constexpr int kNumInt2Tensors = 1;
static const int16_t kInt2TensorIndices[1] = { 13 };

#endif  // PRECISION_CONFIG_H_
